name: ci
on:
  workflow_dispatch: # allow manual trigger
  push:
  pull_request:
permissions:
  security-events: write # Needed to upload-sarif
  contents: read # Needed to clone repo
  actions: read # Potentially needed for private repositories (see https://github.com/github/codeql-action/issues/2117)
jobs:
  call-tf-reusable-workflow:
    uses: atrakic/terraform-test-workflow/.github/workflows/tf-reusable-workflow.yml@main
    with:
      working_directory: tests/tf
